name: Create Release from Tag

on:
  push:
    tags:
      - 'v*.*'  # Trigger on version tags (e.g., v1.0, v1.1)

permissions:
  contents: write  # Allow the action to create releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Fortune Teller Release
            
            Changes in this version:
            - For v1.0: Basic functionality with three moods (happy/sad/neutral)
            - For v1.1: Added the 'stressed' mood and randomized fortune messages
          draft: false
          prerelease: false